project:
  type: website
  output-dir: docs

website:
  title: "Google Embeddings tutorial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: slides/slides.qmd
        text: Presentation
      - text: Demos
        menu:
          - href: satellite-embedding/demo2/landcover-classification.ipynb
            text: "Demo 2: Land Cover Classification with K-Means Clustering (reformatted)"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
